---
# This role installs common base pre-reqs for the ForgeRock stack using yum 
# For Fedora and Centos based images

##
#- name: install epel-repo rpm
#  yum: pkg=/tmp/epel-release.rpm state=installed


# Workaround for https://github.com/ansible/ansible-modules-extras/issues/471
# Remove when Ansible 2.0 package lands
# - name: Install Yum Utilities
#   sudo: true
#   shell: dnf install yum-utils -y
#   args:
#     creates: /usr/bin/repomanage


- name: Install required packages. This takes a while - be patient
  package: name={{item}} state=latest
  with_items:
   - unzip
   - git
   - wget
   - haproxy
   - httpd
   - gpg
   - java-1.8.0-openjdk-headless.x86_64
   - python-pip
   - docker
   - bzip2
   - npm
   - libselinux-python
# PIP is not on Centos 7?

 
# Why do we need httplib2 ?
#- name: Install additional python packages
#  pip: name=httplib2

- pip: name=docker-compose


# Note that 127.0.0.2 is also routable to localhost
- name: Put our fqdn and short hostname in /etc/hosts
  lineinfile: dest="/etc/hosts" line="127.0.0.2 {{openam_fqdn}} {{openam_hostname}}" regexp="{{openam_fqdn}}"  state=present
  
- name: create top level software dir
  file: state=directory path={{install_root}} owner={{fr_user}} mode=0755
  
# Disable SE linux and the firewall. Don't do this production!
#- command: setenforce 0
- selinux: state=disabled

# This is not in Centos7  - so ignore any errors
- service: name=firewalld state=stopped enabled=no
  ignore_errors: yes